# Generated by Django 4.2 on 2025-03-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountcreationfailure",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ACCOUNT CREATION FAILURE",
                "verbose_name_plural": "ACCOUNT CREATION FAILURE",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "TRANSACTIONS",
                "verbose_name_plural": "TRANSACTIONS",
            },
        ),
    ]
