# Generated by Django 4.2 on 2025-02-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsystem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "ACCOUNT SYSTEM",
                "verbose_name_plural": "ACCOUNT SYSTEM",
            },
        ),
    ]
