# Generated by Django 4.2 on 2025-03-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_accountcreationfailure_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
