# Generated by Django 4.2 on 2025-02-17 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_accountsystem_available_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountcreationfailure",
            name="account_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
