# Generated by Django 4.2 on 2025-03-17 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0003_delete_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "transaction_ref",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("REVERSED", "REVERSED"),
                            ("FAILED", "FAILED"),
                            ("SUCCESSFUL", "SUCCESSFUL"),
                        ],
                        default="PENDING",
                        max_length=300,
                    ),
                ),
                (
                    "disbursement_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VFD_WALLET", "VFD"),
                            ("WOVEN_SPARKLE", "WOVEN_SPARKLE"),
                            ("WOVEN_WEMA", "WOVEN_WEMA"),
                            ("MONNIFY", "MONNIFY"),
                        ],
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "beneficiary_account_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "beneficiary_bank_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "beneficiary_bank_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "beneficiary_account_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("balance_before", models.FloatField(blank=True, null=True)),
                ("balance_after", models.FloatField(blank=True, null=True)),
                (
                    "source_account_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "source_account_number",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "source_bank_code",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DISBURSEMENT", "DISBURSEMENT"),
                            ("WITHDRAWAL", "WITHDRAWAL"),
                            ("UTILITIES", "UTILITIES"),
                            ("DEPOSIT", "DEPOSIT"),
                        ],
                        max_length=300,
                        null=True,
                    ),
                ),
                ("narration", models.CharField(blank=True, max_length=500, null=True)),
                ("attempt_payout", models.BooleanField(default=False)),
                ("is_disbursed", models.BooleanField(default=False)),
                ("escrow_id", models.CharField(blank=True, max_length=300, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TRANSACTIONS",
                "verbose_name_plural": "TRANSACTIONS",
                "ordering": ["-created_at"],
            },
        ),
    ]
