# Generated by Django 4.2 on 2025-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_accountcreationfailure_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsystem",
            name="bvn",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
