# Generated by Django 4.2 on 2025-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_remove_accountsystem_bvn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "WALLET SYSTEM",
                "verbose_name_plural": "WALLET SYSTEM",
            },
        ),
        migrations.AlterField(
            model_name="accountsystem",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("FLOAT", "FLOAT"), ("COLLECTION", "COLLECTION")],
                default="COLLECTION",
                max_length=250,
                null=True,
            ),
        ),
    ]
