# Generated by Django 4.2 on 2025-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("AGENT", "agent"), ("USER", "user")],
                default="USER",
                max_length=12,
            ),
        ),
    ]
