# Generated by Django 4.2 on 2025-02-14 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "USER PROFILE",
                "verbose_name_plural": "USERS PROFILE",
            },
        ),
        migrations.CreateModel(
            name="WasteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("PLASTIC", "plastic"),
                            ("METAL", "metal"),
                            ("GLASS", "glass"),
                            ("PAPER", "paper"),
                            ("ORGANIC", "organic"),
                            ("OTHER", "other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("weight", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RECYCLE PRODUCT",
                "verbose_name_plural": "RECYCLE PRODUCT",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup_location", models.CharField(max_length=255)),
                ("pickup_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "pending"),
                            ("COMPLETED", "completed"),
                            ("CANCELLED", "cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "waste_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="waste_auth.wasteproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "SCHEDULE",
                "verbose_name_plural": "SCHEDULES",
                "ordering": ["-created_at"],
            },
        ),
    ]
