# Generated by Django 4.2 on 2025-04-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0004_remove_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
