# Generated by Django 4.2 on 2025-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0004_agentassignment_wasteproduct_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteproduct",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
