# Generated by Django 4.2 on 2025-02-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0005_alter_wasteproduct_quantity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agentassignment",
            options={
                "ordering": ["-assigned_at"],
                "verbose_name": "AGENT ASSIGNMENT",
                "verbose_name_plural": "AGENT ASSIGNMENT",
            },
        ),
        migrations.AlterField(
            model_name="wasteproduct",
            name="pickup_date",
            field=models.DateField(),
        ),
    ]
