# Generated by Django 4.2 on 2025-04-30 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0005_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
    ]
