# Generated by Django 4.2 on 2025-05-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0006_remove_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="constanttable",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 5, 2, 14, 36, 43, 537662, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="constanttable",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="constanttable",
            name="account_provider",
            field=models.CharField(
                choices=[("VFD_WALLET", "VFD"), ("MONNIFY", "MONNIFY")], max_length=10
            ),
        ),
    ]
