# Generated by Django 4.2 on 2025-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "waste_auth",
            "0007_constanttable_created_at_constanttable_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="constanttable",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "CONSTANT TABLE",
                "verbose_name_plural": "CONSTANT TABLE",
            },
        ),
        migrations.AddField(
            model_name="constanttable",
            name="estate_address",
            field=models.JSONField(
                default=[
                    {
                        "estate_name": "Bickersteth",
                        "keywords": ["Bickersteth", "iyana church"],
                    },
                    {
                        "estate_name": "Ogudu GRA",
                        "keywords": ["ogudu", "gra", "ogudu gra"],
                    },
                    {
                        "estate_name": "Magodo Phase 2",
                        "keywords": ["magodo", "phase 2", "magodo shangisha"],
                    },
                ]
            ),
        ),
    ]
