# Generated by Django 4.2 on 2025-02-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0007_alter_wasteproduct_pickup_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstantTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_provider", models.CharField(max_length=300)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
