# Generated by Django 4.2 on 2025-05-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0008_alter_constanttable_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wasteproduct",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="wasteproduct",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="constanttable",
            name="estate_address",
            field=models.JSONField(
                default=[
                    {
                        "estate_name": "Bickersteth",
                        "keywords": ["Bickersteth", "iyana church", "iwaya"],
                    },
                    {
                        "estate_name": "Ogudu GRA",
                        "keywords": ["ogudu", "gra", "ogudu gra"],
                    },
                    {
                        "estate_name": "Magodo Phase 2",
                        "keywords": ["magodo", "phase 2", "magodo shangisha"],
                    },
                ]
            ),
        ),
    ]
