# Generated by Django 4.2 on 2025-02-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0008_constanttable"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bvn",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
