# Generated by Django 4.2 on 2025-05-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0009_remove_wasteproduct_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteproduct",
            name="agent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_waste_products",
                to="waste_auth.recycleagents",
            ),
            preserve_default=False,
        ),
    ]
