# Generated by Django 4.2 on 2025-02-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0009_user_bvn"),
    ]

    operations = [
        migrations.AddField(
            model_name="wasteproduct",
            name="credit_amount",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wasteproduct",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("CREDITED", "CREDITED"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
