# Generated by Django 4.2 on 2025-05-05 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0010_wasteproduct_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wasteproduct",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_waste_products",
                to="waste_auth.recycleagents",
            ),
        ),
    ]
