# Generated by Django 4.2 on 2025-02-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0010_wasteproduct_credit_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wasteproduct",
            old_name="credit_amount",
            new_name="product_value_amount",
        ),
        migrations.AddField(
            model_name="user",
            name="bvn_verified",
            field=models.BooleanField(default=False),
        ),
    ]
