# Generated by Django 4.2 on 2025-05-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0011_alter_wasteproduct_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="recycleagents",
            name="estate",
            field=models.CharField(blank=True, null=True),
        ),
    ]
