# Generated by Django 4.2 on 2025-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "waste_auth",
            "0011_rename_credit_amount_wasteproduct_product_value_amount_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="constanttable",
            name="weight_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
