# Generated by Django 4.2 on 2025-03-17 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0012_constanttable_weight_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentassignment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 17, 10, 15, 4, 120183, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
