# Generated by Django 4.2 on 2025-04-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0013_agentassignment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
