# Generated by Django 4.2 on 2025-04-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("waste_auth", "0014_alter_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecycleAgents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pending_pickups_count", models.IntegerField(default=0)),
                ("total_pickups_count", models.IntegerField(default=0)),
                ("last_pickup_date", models.DateTimeField(blank=True, null=True)),
                ("pickup_success_rate", models.FloatField(default=0.0)),
                ("customer_rating", models.FloatField(default=0.0)),
                ("issues_reported_count", models.IntegerField(default=0)),
                (
                    "identification_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_assigned_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="last_assigned_product",
                        to="waste_auth.wasteproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": " RECYCLE AGENT",
                "verbose_name_plural": "RECYCLE AGENT",
                "ordering": ["-created_at"],
            },
        ),
    ]
