# Generated by Django 4.2 on 2025-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
