# Generated by Django 4.2 on 2025-03-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_metadata'),
    ]

    operations = [
    ]
